name: Build and Release
on:
  push:
    tags:
      - 'v*'  # Trigger only on manual version tags

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '~1.21'
          
      - name: Build
        run: |
          mkdir -p dist
          go build -o dist/stay-alive
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          tag_name: ${{ github.ref_name }}
